name: Validate Node.js projects
on:  
  workflow_dispatch:
  pull_request:
jobs:
  index:
    name: Generate matrix of project directories
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set_output.outputs.matches }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: List directories
      run: find -name '*.js' -type 'f' -printf '%h\n' | uniq
    - name: Set output
      id: set_output
      run: echo "matches=$(find -name '*.js' -type 'f' -printf '%h\n' | uniq | jq --null-input --raw-input --compact-output --sort-keys '[inputs|select(length > 0)]')" >> $GITHUB_OUTPUT
  validate:
    name: Validate Node.js project
    needs: index
    runs-on: ubuntu-latest
    container: node:20.6
    strategy:
      matrix:
        project-directory: ${{ fromJson(needs.index.outputs.projects) }}
    defaults:
      run:
        working-directory: ${{ matrix.project-directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Output Node.js version
        run: node --version
      - name: Output NPM version
        run: npm --version
      - name: Install JS standard rules package
        run: npm install eslint-config-standard --no-save
        working-directory: ../
      - name: Lint and check format with eslint
        run: npx eslint .
  summarize:
    name: All code validated
    needs:
      - index
      - validate
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Evaluate status of jobs
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1